---
- name: copy the artifact from locaal to target machine
  copy:
     src: /home/devops/workspace/ci-cd/applogin/target/applogin-1.3.war
     dest: /tmp

- name: deploy the artifact to tomcat
  copy:
    src: /tmp/applogin-1.3.war
    dest: /opt/tomcat/latest/webapps/
    remote_src: yes
  notify:
    - restart tomcat
