---
- name: Creating a System User
  user:
     name: tomcat
     home: /opt/tomcat
     shell: /bin/false

- name: downloading the tar file
  get_url:
     url: https://www-eu.apache.org/dist/tomcat/tomcat-9/v{{ version }}/bin/apache-tomcat-{{ version }}.tar.gz
     dest: /tmp

- name: extract the tar file to /opt/tomcat
  unarchive:
     src: /tmp/apache-tomcat-{{ version }}.tar.gz
     dest: /opt/tomcat/
     remote_src: yes

- name: create symlink
  file:
     src: /opt/tomcat/apache-tomcat-{{ version }}
     dest: /opt/tomcat/latest
     state: link

- name: change the owner of /opt/tomcat
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    recurse: yes
  
- name: give the executable permissions
  shell: sudo sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'

- name: copy tomcat service file
  template:
     src: tomcat.service.j2
     dest: /etc/systemd/system/tomcat.service

- name: reload demon
  systemd:
     name: tomcat
     state: reloaded
     enabled: yes
  ignore_errors: yes

- name: create role
  lineinfile:
     path: /opt/tomcat/latest/conf/tomcat-users.xml
     insertbefore: '^</tomcat-users>'
     line: "{{ item }}"
  with_items:
    - <role rolename="admin-gui"/>
    - <role rolename="manager-gui"/>
    - <user username="admin" password="admin_password" roles="admin-gui,manager-gui"/>

- name: delete firewall
  lineinfile:
     path: /opt/tomcat/latest/webapps/manager/META-INF/context.xml
     state: absent
     regexp: "{{ item }}"
  with_items:
    - <Valve className="org.apache.catalina.valves.RemoteAddrValve"
    - allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1" />

- name: restart tomcat
  service:
     name: tomcat
     state: restarted




