---
- hosts: all
  become: yes
  tasks:
    - name: install java in debian
      apt:
        name: "{{ java_deb }}"
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"
    
    - name: install java in rhel
      yum:
        name: "{{ java_rhel }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "RedHat"
