---
- hosts: all
  become: true
  tasks:
    - name: installing packages with loops
      apt:
         name: "{{ item }}"
         state: present
      with_items:  
        - git
        - wget
        - tree