---
- hosts: all
  become: true
  tasks:
      - name: installing weberver in deb fjdshifbsfsdbfyus
        apt: 
           name: apache2
           state: latest
        when: ansible_os_family == "Debian"

      - name: installing webserver in rhel ahfidfhsilfslabb
        yum: 
           name: httpd
           state: latest
        when: ansible_os_family == "RedHat"
      
      - name: touch index.html
        file:
           path: /var/www/html/index.html
           state: touch

      - name: copy file 
        file:
           src: index.html
           dest: /var/www/html/

      - name: service restart in deb
        service:
          name: apache2
          state: restarted
        when: ansible_os_family == "Debian"

      - name: service restart in rhel
        service:
          name: httpd
          state: restarted
        when: ansible_os_family == "RedHat"      
