---
- hosts: all
  become: true
  tasks:
      - name: installing weberver in deb 
        apt: 
           name: apache2
           state: latest
        when: ansible_os_family == "Debian"

      - name: installing webserver in rhel 
        yum: 
           name: httpd
           state: latest
        when: ansible_os_family == "RedHat"

      - name: copy file 
        template:
           src: index.j2
           dest: /var/www/html/
        notify:
          - service restart in deb
          - service restart in rhel


  handlers:
      - name: service restart in deb
        service:
          name: apache2
          state: restarted
        when: ansible_os_family == "Debian"

      - name: service restart in rhel
        service:
          name: httpd
          state: restarted
        when: ansible_os_family == "RedHat"      

